### PR TITLE
Fix: seeking in iOS Safari

### LINKED ISSUE #5: [iOS] Tapping on the waveform doesn’t work
It’s not registering the click.

### PR DESCRIPTION
**Pull request by katspaugh**
Resolves #5.

iOS Safari ignores setting the `currentTime` until the audio has been played at least once.
Also if you set the currentTime even once _before_ the audio starts playing, it will always stay at that value. 🤦 

So I've added a `play()` and an immediate `pause()` in the seek function, if the audio hasn't been played yet.

### CODE REVIEW

File: src/player.ts [hunk 1]
```diff
@@ -50,7 +57,17 @@ class Player {
...
+      if (!this.hasPlayedOnce) {
+        this.media.play()
+      }
+
       this.media.currentTime = time
+
+      if (!this.hasPlayedOnce) {
+        this.media.pause()
+        this.hasPlayedOnce = true
+      }
```
Comment (katspaugh) [inline src/player.ts:70]: This is the actual fix, the rest of the changes are just optimizations.

**Comment by entonbiba** [comment]
@katspaugh awesome!
