### PR TITLE
Fix: smoother dragging

### LINKED ISSUE #81: Dragging not smooth
Hi @katspaugh,

Just want to notify you,
I have late comment in this PR https://github.com/katspaugh/wavesurfer.ts/pull/80

I feel the dragging not smooth enough since this PR.

### PR DESCRIPTION
**Pull request by katspaugh**
Resolves #81

The drag event is now called with the relative pointer position instead of a delta. So the playhead basically follows the mouse. This is much simpler and smoother.

I've also made it scroll if you drag past the edge of the container.

@ardiantutomo wdyt?

### CODE REVIEW

**Comment by XyzAQWERTY** [comment]
Hi @katspaugh , 
I found the 'click' event (mouse down that emit click) is not working. I think we still need it
Or maybe we can pass a param for it?

File: src/renderer.ts [hunk 1]
```diff
@@ -77,29 +78,7 @@ class Renderer extends EventEmitter<RendererEvents> {
...
-      let x = e.clientX
-      let firstMove = true
-      const move = (e: MouseEvent) => {
-        const dx = e.clientX - x
-        const rect = this.wrapper.getBoundingClientRect()
-        x = e.clientX
-        if (dx > minDx || dx < -minDx) {
-          if (firstMove) {
-            firstMove = false
-            this.emit('click', (x - rect.left) / rect.width)
```
Comment (ardiantutomo) [inline src/renderer.ts:91]: I feel the same with @XyzAQWERTY,
I think we should put this line back to the code

Comment (katspaugh) [reply src/renderer.ts:91]: I've double-checked and the regular click still works. The event you're commenting on isn't needed anymore as the initial drag will happen at the current mouse position.
